<?php
declare(strict_types=1);
require_once __DIR__ . '/auth.php';
require_role('supervisor');
$errors = []; $success = '';
$editId = filter_var($_GET['editar'] ?? null, FILTER_VALIDATE_INT) ?: null;
$form = ['codigo'=>'','descripcion'=>'','ubicacion'=>''];
if ($editId) { $stmt=db()->prepare('SELECT id,codigo,descripcion,ubicacion FROM carros WHERE id=?'); $stmt->execute([$editId]); $found=$stmt->fetch(); if($found) $form=$found; else $editId=null; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!verify_csrf($_POST['csrf_token'] ?? null)) $errors[]='La sesión expiró. Recarga la página.';
    $action=(string)($_POST['action'] ?? ''); $id=filter_var($_POST['id'] ?? null,FILTER_VALIDATE_INT) ?: null;
    if ($action==='delete' && $id) {
        $check=db()->prepare('SELECT COUNT(*) FROM mantenciones WHERE carro_id=?'); $check->execute([$id]);
        if ((int)$check->fetchColumn()>0) $errors[]='No se puede eliminar este carro porque tiene mantenciones asociadas. Conserva el historial o desactívalo desde la base de datos.';
        else { $delete=db()->prepare('DELETE FROM carros WHERE id=?'); $delete->execute([$id]); $success='Carro eliminado correctamente.'; }
    } elseif ($action==='save') {
        $form=['codigo'=>strtoupper(trim((string)($_POST['codigo']??''))),'descripcion'=>trim((string)($_POST['descripcion']??'')),'ubicacion'=>trim((string)($_POST['ubicacion']??''))];
        if (!preg_match('/^[A-Z0-9][A-Z0-9_-]{0,79}$/',$form['codigo'])) $errors[]='El código debe tener entre 1 y 80 caracteres: letras, números, guion o guion bajo.';
        if (mb_strlen($form['descripcion'])>255 || mb_strlen($form['ubicacion'])>120) $errors[]='La descripción o ubicación supera el límite permitido.';
        if (!$errors) { try { if($id){$stmt=db()->prepare('UPDATE carros SET codigo=?,descripcion=?,ubicacion=? WHERE id=?');$stmt->execute([$form['codigo'],$form['descripcion']?:null,$form['ubicacion']?:null,$id]);$success='Carro actualizado correctamente.';}else{$stmt=db()->prepare('INSERT INTO carros(codigo,descripcion,ubicacion) VALUES(?,?,?)');$stmt->execute([$form['codigo'],$form['descripcion']?:null,$form['ubicacion']?:null]);$success='Carro agregado correctamente.';} $form=['codigo'=>'','descripcion'=>'','ubicacion'=>''];$editId=null;} catch(PDOException $e) { if($e->errorInfo[1]===1062)$errors[]='Ya existe un carro con ese código.';else throw $e; } }
    }
}
$carros=db()->query('SELECT c.id,c.codigo,c.descripcion,c.ubicacion,c.activo,COUNT(m.id) AS total_mantenciones FROM carros c LEFT JOIN mantenciones m ON m.carro_id=c.id GROUP BY c.id ORDER BY c.codigo')->fetchAll();
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administrar carros</title><style>
*{box-sizing:border-box}body{margin:0;background:#eef3f7;color:#183044;font:16px system-ui,sans-serif}.wrap{max-width:1000px;margin:auto;padding:20px}.box,.row{background:#fff;border-radius:14px;padding:20px;margin:15px 0;box-shadow:0 3px 15px #18304412}label{display:block;margin:12px 0 5px;font-weight:700}input,textarea,button{width:100%;padding:11px;border:1px solid #c8d4de;border-radius:8px;font:inherit}textarea{min-height:70px}button{margin-top:15px;background:#136f8a;border:0;color:#fff;font-weight:700}.error{background:#ffe5e5;color:#921c1c;padding:10px;border-radius:8px}.ok{background:#e3f7e9;color:#176b35;padding:10px;border-radius:8px}.row{display:flex;gap:15px;justify-content:space-between;align-items:center;flex-wrap:wrap}.row h2{margin:0;color:#136f8a}.actions{display:flex;gap:8px}.actions a,.actions button{width:auto;margin:0;padding:8px 11px;text-decoration:none}.actions button{background:#fff;color:#a52222;border:1px solid #e0aaaa}.muted{color:#5c7180}.back{color:#136f8a}
</style></head><body><main class="wrap"><a class="back" href="panel.php">← Volver al panel</a><h1>Administrar carros</h1><?php if($errors):?><div class="error"><ul><?php foreach($errors as $eMsg):?><li><?=e($eMsg)?></li><?php endforeach;?></ul></div><?php endif;?><?php if($success):?><p class="ok"><?=e($success)?></p><?php endif;?><section class="box"><h2><?=$editId?'Editar carro':'Agregar carro'?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=e((string)$editId)?>"><label for="codigo">Código</label><input id="codigo" name="codigo" maxlength="80" required value="<?=e($form['codigo'])?>"><label for="descripcion">Descripción</label><input id="descripcion" name="descripcion" maxlength="255" value="<?=e($form['descripcion'])?>"><label for="ubicacion">Ubicación</label><input id="ubicacion" name="ubicacion" maxlength="120" value="<?=e($form['ubicacion'])?>"><button type="submit"><?=$editId?'Guardar cambios':'Agregar carro'?></button></form></section><h2>Carros registrados</h2><?php foreach($carros as $carro):?><article class="row"><div><h2><?=e($carro['codigo'])?></h2><p><?=e($carro['descripcion']??'')?><?= $carro['ubicacion'] ? ' · '.e($carro['ubicacion']) : ''?></p><p class="muted"><?=e((string)$carro['total_mantenciones'])?> mantención(es) asociada(s)</p></div><div class="actions"><a href="carros.php?editar=<?=$carro['id']?>">Editar</a><?php if((int)$carro['total_mantenciones']===0):?><form method="post" onsubmit="return confirm('¿Eliminar este carro definitivamente?');"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$carro['id']?>"><button type="submit">Eliminar</button></form><?php else:?><span class="muted">Protegido por historial</span><?php endif;?></div></article><?php endforeach;?></main></body></html>
