<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';
$user=require_role('operario','supervisor');
$errors=[];$success='';$old=['carro_id'=>'','tipo'=>'Preventiva','descripcion'=>''];
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!verify_csrf($_POST['csrf_token']??null))$errors[]='La sesión del formulario expiró. Recarga la página e inténtalo nuevamente.';
    $old['carro_id']=(string)($_POST['carro_id']??'');$old['tipo']=(string)($_POST['tipo']??'');$old['descripcion']=trim((string)($_POST['descripcion']??''));
    $carroId=filter_var($old['carro_id'],FILTER_VALIDATE_INT);if(!$carroId)$errors[]='Selecciona un carro válido.';
    if(!in_array($old['tipo'],['Preventiva','Correctiva'],true))$errors[]='Selecciona un tipo válido.';
    if($old['descripcion']===''||mb_strlen($old['descripcion'])>10000)$errors[]='La descripción es obligatoria y no puede superar 10.000 caracteres.';
    $fotoNombre=null;$file=$_FILES['foto']??null;
    if($file&&$file['error']!==UPLOAD_ERR_NO_FILE){if($file['error']!==UPLOAD_ERR_OK)$errors[]='La foto no se pudo cargar correctamente.';elseif($file['size']>MAX_UPLOAD_BYTES)$errors[]='La foto supera los 5 MB.';else{$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($allowed[$mime])||!@getimagesize($file['tmp_name']))$errors[]='Solo se permiten imágenes JPG, PNG o WEBP.';else{$fotoNombre=bin2hex(random_bytes(20)).'.'.$allowed[$mime];$dir=__DIR__.'/uploads';if(!is_dir($dir)&&!mkdir($dir,0755,true))$errors[]='No se pudo crear la carpeta de imágenes.';if(!$errors&&!move_uploaded_file($file['tmp_name'],$dir.'/'.$fotoNombre))$errors[]='No se pudo guardar la foto.';}}}
    if(!$errors){$check=db()->prepare('SELECT id FROM carros WHERE id=? AND activo=1');$check->execute([$carroId]);if(!$check->fetchColumn())$errors[]='El carro seleccionado no existe o está inactivo.';}
    if(!$errors){$stmt=db()->prepare('INSERT INTO mantenciones(carro_id,usuario_id,tipo,descripcion,foto) VALUES(?,?,?,?,?)');$stmt->execute([$carroId,$user['id'],$old['tipo'],$old['descripcion'],$fotoNombre]);$success='Mantención registrada correctamente.';$old=['carro_id'=>'','tipo'=>'Preventiva','descripcion'=>''];}elseif($fotoNombre&&is_file(__DIR__.'/uploads/'.$fotoNombre))@unlink(__DIR__.'/uploads/'.$fotoNombre);
}
$carros=db()->query('SELECT id,codigo,descripcion FROM carros WHERE activo=1 ORDER BY codigo')->fetchAll();
require_once __DIR__.'/partials/layout.php';layout_start('Registrar mantención',$user,'registro');
?><a class="module-back" href="panel.php">← Volver al escritorio</a><section class="module-card"><h1>Registrar mantención</h1><p>Ingresa el trabajo realizado y adjunta una fotografía si corresponde.</p><?php if($errors): ?><div class="module-alert error" role="alert"><ul><?php foreach($errors as $error): ?><li><?=e($error)?></li><?php endforeach;?></ul></div><?php endif;?><?php if($success): ?><div class="module-alert success" role="status"><?=e($success)?></div><?php endif;?><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><label for="carro_id">Carro</label><select id="carro_id" name="carro_id" required><option value="">Selecciona un carro</option><?php foreach($carros as $carro): ?><option value="<?=$carro['id']?>" <?=$old['carro_id']==$carro['id']?'selected':''?>><?=e($carro['codigo'])?><?= $carro['descripcion']?' — '.e($carro['descripcion']):''?></option><?php endforeach;?></select><label for="trabajador">Trabajador</label><input id="trabajador" value="<?=e($user['nombre'])?>" readonly><small>Se asociará tu usuario autenticado.</small><label for="tipo">Tipo de mantención</label><select id="tipo" name="tipo" required><option <?=$old['tipo']==='Preventiva'?'selected':''?>>Preventiva</option><option <?=$old['tipo']==='Correctiva'?'selected':''?>>Correctiva</option></select><label for="descripcion">Descripción del trabajo</label><textarea id="descripcion" name="descripcion" maxlength="10000" required><?=e($old['descripcion'])?></textarea><label for="foto">Foto (opcional, máximo 5 MB)</label><input id="foto" type="file" name="foto" accept="image/jpeg,image/png,image/webp" capture="environment"><button type="submit">Guardar mantención</button></form></section><?php layout_end();
