<?php
declare(strict_types=1);
require_once __DIR__ . '/auth.php';
$user = require_login();
$stats = ['carros'=>0,'mes'=>0,'preventivas'=>0,'correctivas'=>0];
$recentes = []; $ultima = null; $dbError = '';
try {
    $stats['carros'] = (int)db()->query('SELECT COUNT(*) FROM carros WHERE activo=1')->fetchColumn();
    $stmt = db()->query("SELECT COUNT(*) AS total, SUM(tipo='Preventiva') AS preventivas, SUM(tipo='Correctiva') AS correctivas FROM mantenciones WHERE realizada_en >= DATE_FORMAT(CURRENT_DATE(), '%Y-%m-01') AND realizada_en < DATE_FORMAT(DATE_ADD(CURRENT_DATE(), INTERVAL 1 MONTH), '%Y-%m-01')");
    $month = $stmt->fetch() ?: [];
    $stats['mes'] = (int)($month['total'] ?? 0); $stats['preventivas'] = (int)($month['preventivas'] ?? 0); $stats['correctivas'] = (int)($month['correctivas'] ?? 0);
    $ultima = db()->query('SELECT m.realizada_en, c.codigo FROM mantenciones m JOIN carros c ON c.id=m.carro_id ORDER BY m.realizada_en DESC, m.id DESC LIMIT 1')->fetch() ?: null;
    $recentes = db()->query('SELECT m.id, m.tipo, m.realizada_en, c.codigo, u.nombre AS trabajador FROM mantenciones m JOIN carros c ON c.id=m.carro_id JOIN usuarios u ON u.id=m.usuario_id ORDER BY m.realizada_en DESC, m.id DESC LIMIT 8')->fetchAll();
} catch (PDOException $exception) {
    $dbError = 'No se pudieron cargar los indicadores. Verifica la conexión con la base de datos.';
}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Panel de mantenciones</title><link rel="stylesheet" href="assets/css/app.css"></head><body>
<header class="topbar"><div class="topbar-inner"><a class="brand" href="panel.php">Mantenciones ferroviarias</a><div class="user-area"><span class="user-name">Hola, <?=e($user['nombre'])?> · <?=e(ucfirst($user['rol']))?></span><a class="logout" href="logout.php">Cerrar sesión</a></div></div></header>
<main class="wrap"><div class="page-heading"><div><h1>Panel de mantenciones</h1><p>Accesos rápidos y actividad reciente de los carros.</p></div></div>
<?php if($dbError):?><div class="error" role="alert"><?=e($dbError)?></div><?php endif;?><section class="metrics" aria-label="Indicadores del sistema"><article class="metric teal"><span class="metric-label">Carros activos</span><strong class="metric-value"><?=number_format($stats['carros'],0,',','.')?></strong><span class="metric-note">Registrados en el sistema</span></article><article class="metric blue"><span class="metric-label">Mantenciones este mes</span><strong class="metric-value"><?=number_format($stats['mes'],0,',','.')?></strong><span class="metric-note">Desde el primer día del mes</span></article><article class="metric green"><span class="metric-label">Preventivas</span><strong class="metric-value"><?=number_format($stats['preventivas'],0,',','.')?></strong><span class="metric-note">Este mes</span></article><article class="metric amber"><span class="metric-label">Correctivas</span><strong class="metric-value"><?=number_format($stats['correctivas'],0,',','.')?></strong><span class="metric-note">Este mes</span></article><article class="metric neutral"><span class="metric-label">Última mantención</span><strong class="metric-value"><?= $ultima ? e(date('d/m',strtotime($ultima['realizada_en']))) : '—' ?></strong><span class="metric-note"><?= $ultima ? 'Carro '.e($ultima['codigo']) : 'Sin registros todavía' ?></span></article></section>
<h2 class="section-title">Acciones principales</h2><section class="actions-grid"><a class="action-card" href="index.php"><h3>Registrar mantención</h3><p>Ingresar un trabajo realizado y adjuntar una fotografía.</p><span class="button">Nueva mantención</span></a><a class="action-card" href="escanear.php"><h3>Escanear carro</h3><p>Usar la cámara del teléfono para abrir el historial.</p><span class="button">Iniciar escáner</span></a><a class="action-card" href="historial.php"><h3>Ver historial</h3><p>Buscar un carro por su código y revisar sus registros.</p><span class="button secondary">Buscar historial</span></a></section>
<?php if($user['rol']==='supervisor'):?><h2 class="section-title">Herramientas de supervisor</h2><section class="actions-grid"><a class="action-card" href="carros.php"><h3>Administrar carros</h3><p>Agregar o modificar la información de los carros.</p><span class="button secondary">Gestionar carros</span></a><a class="action-card" href="generar_qr.php"><h3>Generar códigos QR</h3><p>Descargar o imprimir el QR de cada carro.</p><span class="button secondary">Crear códigos</span></a></section><?php endif;?>
<section class="recent" aria-labelledby="recent-title"><div class="recent-header"><h2 id="recent-title">Actividad reciente</h2><a href="historial.php">Ver todos los historiales</a></div><?php if(!$recentes):?><div class="empty">Todavía no hay mantenciones registradas.</div><?php else:?><div class="table-wrap"><table><thead><tr><th>Carro</th><th>Tipo</th><th>Trabajador</th><th>Fecha</th><th>Acción</th></tr></thead><tbody><?php foreach($recentes as $item):?><tr><td data-label="Carro"><strong><?=e($item['codigo'])?></strong></td><td data-label="Tipo"><span class="type"><?=e($item['tipo'])?></span></td><td data-label="Trabajador"><?=e($item['trabajador'])?></td><td data-label="Fecha"><?=e(date('d/m/Y H:i',strtotime($item['realizada_en'])))?></td><td><a href="historial.php?carro=<?=rawurlencode($item['codigo'])?>">Ver historial</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></main></body></html>
