<?php
declare(strict_types=1);
require_once __DIR__ . '/db.php';
$codigo = trim((string) ($_GET['carro'] ?? ''));
$stmt = db()->prepare('SELECT id, codigo, descripcion, ubicacion FROM carros WHERE codigo = ? AND activo = 1 LIMIT 1');
$stmt->execute([$codigo]); $carro = $stmt->fetch();
if (!$carro) { http_response_code(404); $mantenciones=[]; } else { $stmt=db()->prepare('SELECT m.*, u.nombre AS trabajador FROM mantenciones m JOIN usuarios u ON u.id=m.usuario_id WHERE m.carro_id=? ORDER BY m.realizada_en DESC, m.id DESC'); $stmt->execute([$carro['id']]); $mantenciones=$stmt->fetchAll(); }
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Historial <?=e($codigo)?></title><style>
*{box-sizing:border-box}body{margin:0;background:#eef3f7;color:#183044;font:16px system-ui,sans-serif}.wrap{max-width:900px;margin:auto;padding:20px}.hero,.item{background:#fff;border-radius:14px;padding:20px;margin-bottom:16px;box-shadow:0 3px 15px #18304412}.hero h1{margin-top:0}.meta{color:#5c7180}.item h2{margin:0;color:#136f8a}.badge{display:inline-block;padding:4px 8px;border-radius:999px;background:#dceff4;color:#136f8a;font-size:.85rem;font-weight:700}.photo{max-width:180px;max-height:180px;object-fit:cover;border-radius:10px;margin-top:12px;cursor:zoom-in}.empty,.notfound{padding:18px;background:#fff;border-radius:12px}.notfound{border-left:5px solid #c93636}
</style></head><body><main class="wrap"><?php if(!$carro):?><section class="notfound"><h1>Carro no encontrado</h1><p>El código <strong><?=e($codigo)?></strong> no existe o está inactivo.</p></section><?php else:?><section class="hero"><h1>Historial del carro <?=e($carro['codigo'])?></h1><?php if($carro['descripcion']):?><p><?=e($carro['descripcion'])?></p><?php endif;?><?php if($carro['ubicacion']):?><p class="meta">Ubicación: <?=e($carro['ubicacion'])?></p><?php endif;?><p class="meta"><?=count($mantenciones)?> mantención(es) registrada(s)</p></section><?php if(!$mantenciones):?><p class="empty">Todavía no hay mantenciones registradas.</p><?php else: foreach($mantenciones as $m):?><article class="item"><h2><?=e($m['tipo'])?></h2><p class="meta"><?=e(date('d/m/Y H:i', strtotime($m['realizada_en'])))?> · <?=e($m['trabajador'])?></p><p><?=nl2br(e($m['descripcion']))?></p><?php if($m['foto'] && preg_match('/^[a-f0-9]{40}\.(jpg|png|webp)$/', $m['foto'])):?><a href="uploads/<?=e($m['foto'])?>" target="_blank" rel="noopener"><img class="photo" src="uploads/<?=e($m['foto'])?>" alt="Foto de la mantención"></a><?php endif;?></article><?php endforeach; endif; endif;?></main></body></html>
