<?php
declare(strict_types=1);
require_once __DIR__ . '/auth.php';
$loggedUser = current_user();
$codigo = trim((string)($_GET['carro'] ?? ''));
$stmt = db()->prepare('SELECT id, codigo, descripcion, ubicacion FROM carros WHERE codigo = ? AND activo = 1 LIMIT 1');
$stmt->execute([$codigo]); $carro = $stmt->fetch(); $mantenciones = [];
if ($carro) { $stmt = db()->prepare('SELECT m.*, u.nombre AS trabajador FROM mantenciones m JOIN usuarios u ON u.id=m.usuario_id WHERE m.carro_id=? ORDER BY m.realizada_en DESC, m.id DESC'); $stmt->execute([$carro['id']]); $mantenciones = $stmt->fetchAll(); } else { http_response_code(404); }
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Historial <?=e($codigo)?></title><style>
*{box-sizing:border-box}body{margin:0;background:#eef3f7;color:#183044;font:16px system-ui,sans-serif}.wrap{max-width:900px;margin:auto;padding:20px}.hero,.item{background:#fff;border-radius:14px;padding:20px;margin-bottom:16px;box-shadow:0 3px 15px #18304412}.hero h1{margin-top:0}.meta{color:#5c7180}.item h2{margin:0;color:#136f8a}.photo{max-width:180px;max-height:180px;object-fit:cover;border-radius:10px;margin-top:12px;cursor:zoom-in}.empty,.notfound{padding:18px;background:#fff;border-radius:12px}.notfound{border-left:5px solid #c93636}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.actions a,.actions button{padding:8px 12px;border:1px solid #c8d4de;border-radius:7px;background:#fff;color:#136f8a;text-decoration:none;font:inherit;cursor:pointer}.actions button{color:#a52222;border-color:#e0aaaa}
</style></head><body><main class="wrap"><?php if(!$carro):?><section class="notfound"><h1>Carro no encontrado</h1><p>El código <strong><?=e($codigo)?></strong> no existe o está inactivo.</p></section><?php else:?><section class="hero"><h1>Historial del carro <?=e($carro['codigo'])?></h1><?php if($carro['descripcion']):?><p><?=e($carro['descripcion'])?></p><?php endif;?><?php if($carro['ubicacion']):?><p class="meta">Ubicación: <?=e($carro['ubicacion'])?></p><?php endif;?><p class="meta"><?=count($mantenciones)?> mantención(es) registrada(s)</p></section><?php if(!$mantenciones):?><p class="empty">Todavía no hay mantenciones registradas.</p><?php else: foreach($mantenciones as $m):?><article class="item"><h2><?=e($m['tipo'])?></h2><p class="meta"><?=e(date('d/m/Y H:i', strtotime($m['realizada_en'])))?> · <?=e($m['trabajador'])?></p><p><?=nl2br(e($m['descripcion']))?></p><?php if($m['foto'] && preg_match('/^[a-f0-9]{40}\.(jpg|png|webp)$/', $m['foto'])):?><a href="uploads/<?=e($m['foto'])?>" target="_blank" rel="noopener"><img class="photo" src="uploads/<?=e($m['foto'])?>" alt="Foto de la mantención"></a><?php endif;?><?php if($loggedUser && $loggedUser['rol']==='supervisor'):?><div class="actions"><a href="editar_mantencion.php?id=<?=$m['id']?>">Editar</a><form method="post" action="eliminar_mantencion.php" onsubmit="return confirm('¿Eliminar esta mantención definitivamente?');"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$m['id']?>"><input type="hidden" name="carro" value="<?=e($codigo)?>"><button type="submit">Eliminar</button></form></div><?php endif;?></article><?php endforeach; endif; endif;?></main></body></html>
